environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: C:\Python37-x64\python.exe
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: C:\Python36\python.exe

before_build:
  - "%PYTHON% --version"
  - "%PYTHON% -m pip install -U setuptools pip"

build_script:
  - "%PYTHON% -m pip install -e ."

test_script:
  - "%PYTHON% runtests.py"

deploy: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'
