version: 2.1
executors:
  nix:
    docker:
      - image: nixos/nix:2.2.1
    environment:
      SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
jobs:
  build:
    executor: nix
    parameters:
      attribute:
        type: string
    steps:
      - checkout
      - run:
          name: Initial setup
          command: |
            ln -s ${NIX_SSL_CERT_FILE} ${SSL_CERT_FILE}
            # We need at least busybox 1.29 to fix a hardlink/symlink bug in tar
            nix-env -iA nixpkgs.busybox
      - run:
          name: Check dependencies
          command: nix-store -q --references $(nix-instantiate -A << parameters.attribute >>) | grep llvm > deps.txt
      - restore_cache:
          keys:
            - v1-{{ checksum "deps.txt" }}
      - run:
          name: Set up Cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
            cachix use bcdb
      - run:
          name: Install dependencies
          command: nix-store --realise --cores 4 $(cat deps.txt) | cachix push bcdb
      - save_cache:
          key: v1-{{ checksum "deps.txt" }}
          paths:
            - /nix
      - run:
          name: Build and test BCDB
          command: nix-build -A << parameters.attribute >>
workflows:
  build:
    jobs:
      - build:
          name: build-llvm4
          attribute: "bcdb-llvm4"
      - build:
          name: build-llvm5
          attribute: "bcdb-llvm5"
      - build:
          name: build-llvm6
          attribute: "bcdb-llvm6"
      - build:
          name: build-llvm7
          attribute: "bcdb-llvm7"
      - build:
          name: build-llvm8
          attribute: "bcdb-llvm8"
      - build:
          name: build-clang
          attribute: "bcdb-clang"
