name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        variant:
        - bcdb-llvm5
        - bcdb-llvm6
        - bcdb-llvm7
        - bcdb-llvm8
        - bcdb-llvm9
        - bcdb-llvm10
        - bcdb-clang
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@v2
      with:
        name: bcdb
        attributes: '${{ matrix.variant }}'
    - name: Slack Notification
      if: failure()
      uses: homoluctus/slatify@master
      with:
        job_name: '*Test*'
        commit: true
        type: ${{ job.status }}
        url: ${{ secrets.SLACK_WEBHOOK }}
        token: ${{ secrets.GITHUB_TOKEN }}
