name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        variant:
        - bcdb-llvm6
        - bcdb-llvm7
        - bcdb-llvm8
        - bcdb-llvm9
        - bcdb-llvm10
        - bcdb-llvm11
        - bcdb-clang
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v6
      with:
        name: bcdb
    - run: nix-build -A ${{ matrix.variant }}
    - name: Slack Notification
      if: failure()
      uses: homoluctus/slatify@v2.1.2
      with:
        job_name: '*Test*'
        commit: true
        type: ${{ job.status }}
        url: ${{ secrets.SLACK_WEBHOOK }}
        token: ${{ secrets.GITHUB_TOKEN }}
