name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        variant:
        - bcdb-llvm9
        - bcdb-llvm10
        - bcdb-llvm11
        - bcdb-llvm12
        - bcdb-llvmAlive
        - bcdb-clang-asan
        - bcdb-without-nng
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
    - uses: cachix/cachix-action@v10
      with:
        name: bcdb
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A ${{ matrix.variant }}
    - name: Slack Notification
      if: failure()
      uses: lazy-actions/slatify@v3.0.0
      with:
        job_name: '*Test*'
        commit: true
        type: ${{ job.status }}
        url: ${{ secrets.SLACK_WEBHOOK }}
        token: ${{ secrets.GITHUB_TOKEN }}
